src/GeekComparer.Web/Controllers/SmartphoneCompareController.cs
using GeekComparer.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace GeekComparer.Web.Controllers;

public class SmartphoneCompareController : Controller
{
    private List<Smartphone> _smartphones = new List<Smartphone>()
    {
        new() { Id = 1, Brand = "Apple", Model = "IPhone Xr", ReleaseDate = "May 2019" },
        new() { Id = 2, Brand = "Realme", Model = "GT Neo 5 SE", ReleaseDate = "May 2023" },
        new() { Id = 3, Brand = "OnePlus", Model = "Nord 2", ReleaseDate = "January 2022" },
        new() { Id = 4, Brand = "Xiaomi", Model = "5S", ReleaseDate = "February 2022" },
        new() { Id = 5, Brand = "Oppo", Model = "Reno 8", ReleaseDate = "March 2022" },
        new() { Id = 6, Brand = "Google", Model = "Pixel 6a", ReleaseDate = "April 2022" },
        new() { Id = 7, Brand = "Samsung", Model = "A54", ReleaseDate = "May 2022" },
        new() { Id = 8, Brand = "Nothing", Model = "Phone 2", ReleaseDate = "June 2022" },
        new() { Id = 9, Brand = "Asus", Model = "ZenPhone 8", ReleaseDate = "July 2022" },
    };

    [HttpGet]
    public IActionResult Index(SmartphoneViewModel vm)
    {
        vm.Smartphones = _smartphones;

        if (vm.Comparison.Count == 0)
            vm.Comparison = new List<Smartphone>()
            {
                new() { Id = 1, Brand = "Apple", Model = "IPhone Xr", ReleaseDate = "May 2019" },
            };

        return View(vm);
    }

    [HttpPost]
    public IActionResult AddToComparison(string smartphoneChoice, int[] comparisonIds)
    {
        var vm = new SmartphoneViewModel();
        vm.Smartphones = _smartphones;

        foreach (var id in comparisonIds)
            vm.Comparison.Add(_smartphones.First(s => s.Id == id));

        var brand = smartphoneChoice.Split(' ')[0];
        var modelSplitted = smartphoneChoice.Split(' ').Skip(1);
        var model = string.Join(' ', modelSplitted);

        vm.Comparison.Add(_smartphones.Where(s => s.Brand == brand).First(s => s.Model == model));

        return View("Index", vm);
    }

    [HttpPost]
    public IActionResult DeleteFromComparison(int idToDelete, int[] comparisonIds)
    {
        var vm = new SmartphoneViewModel();
        vm.Smartphones = _smartphones;

        foreach (var id in comparisonIds)
            vm.Comparison.Add(_smartphones.First(s => s.Id == id));

        vm.Comparison.Remove(_smartphones.First(s => s.Id == idToDelete));

        return View("Index", vm);
    }
}

src/GeekComparer.Web/Views/SmartphoneCompare/Index.cshtml
@model SmartphoneViewModel

@{
    ViewData["Title"] = "TEST";
}

<form method="post" asp-controller="SmartphoneCompare" asp-action="AddToComparison">
    <div>
        <div class="row mt-3 mb-3 ">
            <div class="form-label">Add phone to compare</div>
            <div class="col col-md-3">
                <input type="text"
                       id="smartphones-search"
                       class="form-control"
                       placeholder="Add another..."
                       list="all-smartphones"
                       name="SmartphoneChoice"
                       maxlength="20"/>

                @foreach (var sm in Model.Comparison)
                {
                    <input type="hidden" name="comparisonIds" value="@sm.Id"/>
                }

            </div>
            <div class="col col-md-1">
                <button type="submit" class="btn btn-outline-primary">
                    <i class="bi bi-plus-lg"></i>
                </button>
            </div>
        </div>
    </div>
</form>


<datalist id="all-smartphones">
    @foreach (var phone in Model.Smartphones)
    {
        <option value="@phone.Brand @phone.Model"></option>
    }
</datalist>

<div class="tablecontainer">
    <table>
        <thead>

        <th>
            Smartphone
        </th>

        @foreach (var phone in Model.Comparison)
        {
            <th>

                <form method="post" asp-controller="SmartphoneCompare" asp-action="DeleteFromComparison">

                    <input type="hidden" value="@phone.Id" name="idToDelete"/>
                    @foreach (var sm in Model.Comparison)
                    {
                        <input type="hidden" name="comparisonIds" value="@sm.Id"/>
                    }

                    @phone.Brand @phone.Model
                    <button type="submit" class="btn btn-outline-danger btn-sm">
                        <i class="bi bi-x-lg"></i>
                    </button>

                </form>

            </th>
        }

        </thead>

        <tbody>
        <tr class="text-center">
            <th>
                Id
            </th>
            @foreach (var smartphone in Model.Comparison)
            {
                <td>
                    @smartphone.Id
                </td>
            }
        </tr>

        <tr class="text-center">
            <th>
                Brand
            </th>
            @foreach (var smartphone in Model.Comparison)
            {
                <td>
                    @smartphone.Brand
                </td>
            }
        </tr>

        <tr class="text-center">
            <th>
                Model
            </th>
            @foreach (var smartphone in Model.Comparison)
            {
                <td>
                    @smartphone.Model
                </td>
            }
        </tr>

        <tr class="text-center">
            <th>
                Release Date
            </th>
            @foreach (var smartphone in Model.Comparison)
            {
                <td>
                    @smartphone.ReleaseDate
                </td>
            }
        </tr>

        @for (var i = 0; i < 20; i++)
        {
            <tr class="text-center">
                <th>
                    Head
                </th>

                @for (var j = 0; j < Model.Comparison.Count; j++)
                {
                    <td>
                        @Model.Comparison[j].ReleaseDate
                    </td>
                }
            </tr>
        }

        </tbody>
    </table>
</div>

<style>

table {
	white-space: nowrap;
	overflow-y: scroll;
	/*border-collapse: collapse;*/
}

    /* Use overflow:scroll on your container to enable scrolling: */
    
div.tablecontainer {
    height: 800px;
    overflow-x: scroll;
}
    
    
    /* Use position: sticky to have it stick to the edge
     * and top, right, or left to choose which edge to stick to: */
    
thead th {
    position: sticky;
    top: 0;
}
    
tbody th {
    position: sticky;
    left: 0;
}
    
thead th:first-child {
    left: 0;
    z-index: 2;
}

thead th {
    background: #FFF;
    color: #000;
    z-index: 1;
    box-shadow: 1px 1px 0 0 #ccc;
}
    
tbody th {
    background: #FFF;
    border-right: 1px solid #CCC;
      /* Browsers tend to drop borders on sticky elements, so we emulate the border-right using a box-shadow to ensure it stays: */
    box-shadow: 1px 1px 0 0 #ccc;
}
    
td, th {
    padding: 0.5em;
}

</style>